Build an Authentication System with Nextjs and Directus
directus-community/guest-authoring pull request #25
Opened 2023-12-10 11:12 UTC by 0xJamin

This is the first draft of the article: *Build an Authentication System with Nextjs and Directus* 

This PR fixes #21

2023-12-12 12:31 UTC, phazonoverload requested changes
Good start with lots of small notes added. Some big/global things:

1. Make sure to name products properly - it's Node.js and NextAuth.js. Update throughout. 
2. This post tries to be comprehensive, but as a result covers a lot of other topics that aren't part of this project - like setting up a database, running Directus locally, and introducing Tailwind syntax. I've commented where important, but let's strip this right back to the basics and just focus on NextAuth.js implementation. In summary that means:
    1. Link to Directus getting started without spinning up a DB and local project. A user can do that and come back, or may already have a project.
    2. Remove Tailwind and redo screenshots with unstyled pages.
4. Remove hardcoded links to locally-running Directus. You can refer to `your-directus-project-url/admin/users`, for example.
5. Please title case all headers.
6. In our blog, we use the word directory over folder. Please update these.
7. When referring to file or directory names, use `inline-code`

Great post, very interesting. Excited to shorten it and make it punchy.

2023-12-12 12:31 UTC, phazonoverload commented on next-auth-with-directus/index.md
> +Next, navigate to  Settings > Access Control > Public (<http://localhost:8055/admin/settings/roles/public>); here, you'd want to set a permission rule that whenever a visitor visits your website and
This is mostly an exercise in being very direct. You are instructing with only the required explanation, without too much detail that could be confusing.

2023-12-12 12:31 UTC, phazonoverload commented on next-auth-with-directus/index.md
> +With all the required dependencies installed, you can start building the components for the frontend application.
Remove this. It's clear we've moved on from boilerplating to implementation - you don't need to be as explicit as to call it out.

2023-12-12 12:31 UTC, phazonoverload commented on next-auth-with-directus/index.md
> +This TailwindCSS styled form will serve as the `AuthForm` for both the registration and login pages.
Remove tailwind

2023-12-12 12:31 UTC, phazonoverload commented on next-auth-with-directus/index.md
> +Kudos 🥳, you've just implemented a login functionality using `next-auth` in your Nextjs application with Directus.
Remove emojis from prose

2023-12-12 12:31 UTC, phazonoverload commented on next-auth-with-directus/index.md
> +Go ahead and test it. When a user logs in, it will go to the dashboard page (`/`)
Define 'it' - `the application will navigate to`

2023-12-12 12:31 UTC, phazonoverload commented on next-auth-with-directus/index.md
> +An authentication system is only complete with a forgotten password reset functionality.
Remove this and jump into the instructions

2023-12-12 12:31 UTC, phazonoverload commented on next-auth-with-directus/index.md
> +The email your users will receive should look like this screenshot above
Remove this - it's customization beyond the scope of implementing auth

2023-12-12 12:31 UTC, phazonoverload commented on next-auth-with-directus/index.md
> +
Add the note here about customizing the `directus_users` data model to contain extra fields

2023-12-18 14:24 UTC, 0xJamin commented
Hi @phazonoverload  I fixed all the requested changes on this

2023-12-22 09:02 UTC, phazonoverload commented
Great! Just to set expectations, I'll roll back around to this meaningfully first week of Jan. Have a lovely end of the year!

2023-12-22 10:20 UTC, 0xJamin commented
Hi @phazonoverload that's fine

2024-01-03 12:55 UTC, phazonoverload commented
Solid post. I'm very happy we removed a bunch of the auxiliary content to focus on just the titled topic.

Thank you for writing this, and I'm happy to consider it done in it's current state. I'll schedule it in to be published. 

This repo is just for authoring/reviewing - the actual piece will be published via a Directus project, so I'll take it from here. I'll close this issue to keep the main branch clean, but this is a acceptance of your work.

Could you email me at [kevin@directus.io](mailto:kevin@directus.io) and I'll share what we need to get you paid.

2024-01-03 12:55 UTC, closed without merging

2024-01-10 09:57 UTC, codejagaban commented
Hi @phazonoverload, I sent an email last week and haven't received any updates yet.

Looking forward to your response.

2024-01-10 09:59 UTC, phazonoverload commented
Odd, I can't find anything and don't remember seeing it. Can you do so again, or message me on the Directus Discord?

2024-01-10 10:02 UTC, codejagaban commented
Let me send you a message on Discord them