How to Deploy Directus to AWS EC2
directus-community/guest-authoring pull request #42
Opened 2024-01-08 01:16 UTC by 0xJamin

This PR fixes #31 

Apologies for the late update, I add an issue with AWS that I was unable to resolve early enough

2024-01-11 11:06 UTC, phazonoverload requested changes
Excellent post. Most of my review points are tiny.

2024-01-11 11:06 UTC, phazonoverload commented on directus-aws/index.md
> +![EC2 instance connect page](ec2-connect.png)
remove, clear instruction above

2024-01-11 11:06 UTC, phazonoverload commented on directus-aws/index.md
> +```
````suggestion
Grant permission to run the `docker-compose` command without using the `sudo` command, and start the docker service:

```bash
sudo chmod +x /usr/local/bin/docker-compose
sudo service docker start
```
````

2024-01-11 11:06 UTC, phazonoverload commented on directus-aws/index.md
> +touch docker-compose.yml && vim docker-compose.yml
Please replace with `nano` - no point trapping people in a text editor. Please make sure to do this throughout.

2024-01-11 11:06 UTC, phazonoverload commented on directus-aws/index.md
> +      DB_PASSWORD: "YOUR_DB_PASSWORD"
You missed the part where you explain where these values can be found. And the DB_HOST

2024-01-11 11:06 UTC, phazonoverload commented on directus-aws/index.md
> +Press the `esc` key to exit the insert mode and press `:` followed along with `wq` to quite the `vim` editor
Obviously remove this once we move to using a sane text editor

2024-01-11 11:06 UTC, phazonoverload commented on directus-aws/index.md
> +![An EC2 instance properties page](ec2-public.png)
```suggestion
![An EC2 instance properties page showing the location of the Public IPv4 DNS value](ec2-public.png)
```

2024-01-11 11:06 UTC, phazonoverload commented on directus-aws/index.md
> +## Set up AWS s3 (optional)
```suggestion
## Set up AWS S3 (optional)
```

2024-01-11 11:06 UTC, phazonoverload commented on directus-aws/index.md
> +![An AWS s3 page with list of buckets and a button to create a new bucket](new-bucket.png)
Remove

2024-01-11 11:06 UTC, phazonoverload commented on directus-aws/index.md
> +When creating a new bucket, ensure ACLs are disabled and public access is blocked for the bucket for privacy (you can update these settings to suit your needs).
Explain briefly what ACLs are

2024-01-11 11:06 UTC, phazonoverload commented on directus-aws/index.md
> +  STORAGE_S3_REGION: YOUR_PREFERRED_REGION
Again, help users know where the S3-specific values are

2024-01-11 11:06 UTC, phazonoverload commented on directus-aws/index.md
> +- Consider implementing a load balancer for scaling the incoming requests on your directus application.
And it might be worth noting the limitations here against Cloud in a reasonable way: no backups, rolling updates, restart logic if it crashes.

2024-01-15 22:13 UTC, codejagaban commented
Hi @phazonoverload I updated all the changes requested

2024-01-16 13:16 UTC, phazonoverload approved these changes
Thank you for writing this, and I'm happy to consider it done in it's current state. I'll schedule it in to be published. 

As this is not your first post for us, you know the process from here. Please send me an invoice for the agreed amount. 

Thanks!

2024-01-16 13:16 UTC, phazonoverload commented on directus-aws/index.md
> +![An AWS RDS database creation page with options to configure the database](create-db.png)
Note to self: remove this and bold 'Standard create' in paragraph above.

2024-01-16 13:16 UTC, phazonoverload commented on directus-aws/index.md
> +In the settings options, create a name for your database instance and a username and password credentials to log in to the database (You'll use these credentials to log in via Directus).
```suggestion
In the settings options, create a name for your database instance and a username and password credentials to connect to the database (You'll use these credentials to connect via Directus).
```

2024-01-16 13:16 UTC, phazonoverload commented on directus-aws/index.md
> +![An AWS RDS database creation page with options to configure the settings and login method of the database](db-settings.png)
Note to self: also remove. Description is good above.

2024-01-16 13:16 UTC, phazonoverload commented on directus-aws/index.md
> +![An AWS RDS database creation page to set up the connectivity options to the database](db-connection.png)
Note to self: Once again, for no additional info and burden of updating screenshots, remove.

2024-01-16 13:17 UTC, closed without merging

2024-01-29 08:37 UTC, phazonoverload commented
Question on this based on feedback: 

> sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
> 
> fails due to previously configured outbound rules does not include 80/8080 ports

How might we update this article to fix this?

2024-01-29 12:14 UTC, codejagaban commented
> Question on this based on feedback:
> 
> > sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
> > fails due to previously configured outbound rules does not include 80/8080 ports
> 
> How might we update this article to fix this?

By default, a security group includes an outbound rule allowing all outbound traffic. This ensures that the VPS can communicate and install any package.

We can update the outbound rules table in the article to include rules to allow outbound traffic if isn't present:

| Name  | Security group rule ID | IP version | Type | Protocol | Port Range | Source |
| --- | --- | --- | --- | --- | --- | --- |
| -  | your default security group | IPv4 | PostgreSQL | TCP | 5432 | 0.0.0.0/0 |
| -  | your default security group | IPv4 | HTTPS | TCP | 443 | 0.0.0.0/0 |
| -  | your default security group | IPv4 | HTTP | TCP | 80 | 0.0.0.0/0 |