Deploying Directus to Microsoft Azure Web Apps
directus-community/guest-authoring pull request #57
Opened 2024-01-16 18:58 UTC by GeoSegun

My complete submission

Closes #40

2024-01-17 09:06 UTC, GeoSegun commented
Thanks, Kevin.

2024-01-24 12:04 UTC, phazonoverload requested changes
Great post. A lot of my suggestions were about being more clear and direct, focusing on just the parts that matter to a Directus user deploying on Azure specifically.

2024-01-24 12:04 UTC, phazonoverload commented on directus-az/index.md
> +Directus is successfully deployed and can be visited via the **Default domain** in the Azure web app. Leveraging the power of Directus' Backend as a Service (BaaS) solution, you can now benefit from
```suggestion
When creating a Web App, you will step through multiple configuration pages. Here are the important settings:

### Basics

- Subscription/Resource Group: select the same resource group we created and used earlier.
- Publish: Select "Docker Container". 

![Azure Web App Basic Configuration](web-configuration.png)

### Docker

Select Docker Compose and Docker Hub as the source for your app's configuration. Set the Docker Hub Access Type to Public and upload your `docker-compose.yml` file prepared earlier.

![Docker congiguration settings](docker-configuration.png)

Following the creation of the Web App Resource, Directus is now successfully deployed and can be visited via the default domain in the Azure Web App page. 
```

2024-01-24 12:04 UTC, phazonoverload commented on directus-az/index.md
> +## Trouble Shooting Tips
```suggestion
## Troubleshooting Tips
```

2024-01-24 12:04 UTC, phazonoverload commented on directus-az/index.md
> +This tutorial has guided you through setting up a resource group, configuring Azure Database for PostgreSQL, and deploying Directus using Docker on Azure Web App. The integration of these technologie
```suggestion
This tutorial has guided you through setting up a resource group, configuring Azure Database for PostgreSQL, and deploying Directus using Docker on an Azure Web App.
```

2024-01-24 19:18 UTC, GeoSegun commented
Thanks, Kevin.
I have successfully made the changes and also made a PR

2024-01-26 13:20 UTC, closed without merging