Build a Website with Remix and Directus SDK
directus-community/guest-authoring pull request #60
Opened 2024-01-19 03:37 UTC by codejagaban

Closes #44

2024-01-24 11:21 UTC, phazonoverload requested changes
Light changes and suggestions needed. If you continue writing for us please take some time to proofread content before submitting it for review. Thanks!

2024-01-24 11:21 UTC, phazonoverload commented on directus-remix/index.md
> +[Remix](https://remix.run/) is a React.js framework that  helps you deliver websites that are fast, slick, and have resilient user experience. In this tutorial, you will learn how to build a website
```suggestion
[Remix](https://remix.run/) is a React.js framework that provides many conveniences useful when building websites. In this tutorial, you will learn how to build a website using Directus as a Headless CMS. You will store, retrieve, and use global metadata such as the site title, create new pages dynamically based on Directus items, and build a blog.
```

This suggestion removes overpromoting or selling Remix and just explains what it is plainly.

2024-01-24 11:21 UTC, phazonoverload commented on directus-remix/index.md
> +- Some knowledge of TypeScript and React
```suggestion
- Some knowledge of TypeScript and React.
```

2024-01-24 11:21 UTC, phazonoverload commented on directus-remix/index.md
> +npx create-remix@latest
Please pin to a version so this post doesn't fall out of date immediately.

2024-01-24 11:21 UTC, phazonoverload commented on directus-remix/index.md
> +```
```suggestion
Once initialized, open the directory in a code editor and delete all the contents in the `app/routes/_index.tsx` file.
```

2024-01-24 11:21 UTC, phazonoverload commented on directus-remix/index.md
> +
Install the SDK here.

2024-01-24 11:21 UTC, phazonoverload commented on directus-remix/index.md
> +## Create a Helper for the SDK
```suggestion
## Create a Directus SDK Helper
```

2024-01-24 11:21 UTC, phazonoverload commented on directus-remix/index.md
> + By default, new collections are not accessible to the public. Navigate to Settings -> Roles & Permissions -> Public and give Read access to the Global collection.
```suggestion
 By default, new collections are not accessible to the public. Navigate to Settings -> Access Control -> Public and give Read access to the Global collection.
```

2024-01-24 11:21 UTC, phazonoverload commented on directus-remix/index.md
> +### Setup Dynamic Routes in Astro
I know you're dong a few of these, but please take some time to ensure copy/paste work is then adjusted appropriately!

2024-01-24 11:21 UTC, phazonoverload commented on directus-remix/index.md
> +Create a text input field called `title` and a WYSIWYG input field called `content`. In Roles & Permissions, give the Public role read access to the new collection.
```suggestion
Create a text input field called `title` and a WYSIWYG input field called `content`. In the Access Control settings, give the Public role read access to the new collection.
```

2024-01-24 11:21 UTC, phazonoverload commented on directus-remix/index.md
> +In Roles & Permissions, give the Public role read access to the `authors`, `posts`, and `directus_files` collections.
```suggestion
In the Access Control settings, give the Public role read access to the `authors`, `posts`, and `directus_files` collections.
```

2024-01-24 11:21 UTC, phazonoverload commented on directus-remix/index.md
> +Display the fetched data in HTML:
It's not clear which file this code should be put in - make it clear it's at the bottom of the same file

2024-01-24 11:21 UTC, phazonoverload commented on directus-remix/index.md
> +While not strictly Directus-related, there are now several pages that aren't linked to each other. Update the `Layout.astro` file to include a navigation. Don't forget to use your specific page slugs
Again, this says Astro. Copying and pasting is a convenience but has to come with the due diligence that work is updated for a specific use case.

2024-01-24 13:04 UTC, codejagaban commented
Hi @phazonoverload, apologies for the typos 

I did a proofread and made the needed changes locally, I didn't know I didn't commit them to GitHub.

I just updated all required changes

2024-01-26 13:16 UTC, phazonoverload commented
Happy to accept this as-is. Thank you. You know what to do next (can we try moving this back to email?)

2024-01-26 13:16 UTC, closed without merging